DROP TABLE IF EXISTS ads;

CREATE TABLE ads (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    title VARCHAR(250) NOT NULL,
    description VARCHAR(250) NOT NULL,
    category VARCHAR(250) DEFAULT NULL,
    date TIMESTAMP DEFAULT CURRENT_TIMESTAMP

);

